---
include:
  # XIAO nRF52840 settings reset
  - board: xiao_ble//zmk
    shield: settings_reset

  # nice!nano / Pro Micro nRF52840 settings reset
  - board: nice_nano//zmk
    shield: settings_reset

  # -------------------------
  # Regular Hana split
  # -------------------------

  - board: xiao_ble//zmk
    shield: hana_central_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: xiao_ble//zmk
    shield: hana_peripheral_right

  # -------------------------
  # Hana dongle mode
  # -------------------------

  # Hana dongle - no display
  - board: nice_nano//zmk
    shield: hana_central_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  # Hana dongle - 128x64 OLED
  - board: nice_nano//zmk
    shield: hana_central_dongle_128x64 dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  # Hana dongle - 128x32 OLED
  - board: nice_nano//zmk
    shield: hana_central_dongle_128x32 dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: xiao_ble//zmk
    shield: hana_peripheral_left
    cmake-args: -DCONFIG_HANA_CHARGE_STATUS=y

  - board: xiao_ble//zmk
    shield: hana_peripheral_right
    cmake-args: -DCONFIG_HANA_CHARGE_STATUS=y
