manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    - name: sukumar
      url-base: https://github.com/Sukumar002

    - name: danielsvane
      url-base: https://github.com/danielsvane

  projects:
    - name: zmk
      remote: danielsvane
      revision: customkeyboards
      import: app/west.yml

    - name: zmk-dongle-display
      remote: sukumar
      revision: main

  self:
    path: config
