manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    - name: sukumar
      url-base: https://github.com/Sukumar002

  projects:
    - name: zmk
      remote: sukumar
      revision: 6c3f06820eb0e98c41b0c02a75cd77a7fcdff366
      import: app/west.yml

    - name: zmk-dongle-display
      remote: sukumar
      revision: main

  self:
    path: config
