manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    - name: sukumar
      url-base: https://github.com/Sukumar002

  projects:
    - name: zmk
      remote: sukumar
      revision: hana-combo-names
      import: app/west.yml

    - name: zmk-dongle-display
      remote: sukumar
      revision: main

  self:
    path: config
