# Explicit split-central role
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Allow the dongle to maintain both split peripheral links plus host profiles
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# display
# CONFIG_ZMK_DISPLAY=y
# CONFIG_ZMK_IDLE_TIMEOUT=60000
# CONFIG_BT_BAS=n
# CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
